### ISSUE TITLE
Sometimes the bot will not update my SR properly

### ISSUE THREAD

**Issue by steven-liu** [snakelayer/discord-oversessions#1]
After playing some games, I expect to see a new message reflecting my SR changes, but I don't. It doesn't seem to have a pattern.

**Comment by snakelayer** [comment]
the handler for player updates has been synchronized, which hopefully addresses this issue (https://github.com/snakelayer/discord-oversessions/commit/428a6eb50671cb8d8ac881f2a42b651d272d1b78)
