### ISSUE TITLE
Error on go get

### ISSUE THREAD

**Issue by Jk8c19** [snakelayer/discord-oversessions#2]
Error when attempting to get, I'm not familiar with go so if this is an installation error on my part apologies in advance.
```
REDACTED:~# go get github.com/snakelayer/discord-oversessions
# github.com/snakelayer/discord-oversessions/owbot/discord
go/src/github.com/snakelayer/discord-oversessions/owbot/discord/discord.go:133:19: cannot convert "voice" to type discordgo.ChannelType
go/src/github.com/snakelayer/discord-oversessions/owbot/discord/discord.go:133:19: invalid operation: channel.Type == "voice" (mismatched types discordgo.ChannelType and string)

```

**Comment by snakelayer** [comment]
Not your fault. This was written on an earlier version of Go than you have installed. I'll update it when I get the chance.

**Comment by snakelayer** [comment]
Slight correction to my previous statement: it's not the version of Go, but the version of [bwmarrin/discordgo](https://github.com/bwmarrin/discordgo) that was updated. In any case, https://github.com/snakelayer/discord-oversessions/commit/87d25f1b08968f437d4d3dca09b2e6ab71cbb56c should resolve this issue.
